#!/bin/bash

# Aggressive Cleanup - Remove All Temporary Documentation
set -e

echo "🧹 AGGRESSIVE CLEANUP - Removing Temporary Documentation"
echo "========================================================"
echo ""

# Create backup directory
BACKUP_DIR="./cleanup_aggressive_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"

echo "📦 Backup location: $BACKUP_DIR"
echo ""

# Function to move to backup
move_file() {
    if [ -f "$1" ]; then
        mv "$1" "$BACKUP_DIR/"
        echo "  📦 Moved: $1"
    fi
}

echo "Category 1: Old Status/Summary Files (Temporary)"
echo "------------------------------------------------"
move_file "EVERYTHING_COMPLETE.md"
move_file "FINAL_CORRECTION_SUMMARY.md"
move_file "FINAL_DEPLOYMENT_STATUS.md"
move_file "FINAL_FIX_DEPLOY.md"
move_file "FINAL_STATUS.md"
move_file "FINAL_UI_IMPROVEMENTS.md"
move_file "FIX_APPLIED_RESTART_BACKEND.md"
move_file "FRONTEND_BACKEND_CONNECTION_STATUS.md"
move_file "FRONTEND_VERIFICATION.md"
move_file "GCP_STATUS_ANALYSIS_FINAL.md"
move_file "IMMEDIATE_ACTIONS_CHECKLIST.md"
move_file "IMPLEMENTATION_STATUS.md"
move_file "NUMBERING_FIX_SUMMARY.md"
move_file "READY_TO_REDEPLOY.md"
move_file "SCHEMA_FIX_SUMMARY.md"
move_file "STATUS.txt"
move_file "SYSTEM_STATUS_FINAL.md"
move_file "SYSTEM_STATUS_SUMMARY.md"
move_file "VERSION_1_COMPLETE_STATUS.md"
move_file "VERSION_2_PROGRESS_SUMMARY.md"

echo ""
echo "Category 2: Old UI/Layout Documentation (Replaced)"
echo "--------------------------------------------------"
move_file "HORIZONTAL_LAYOUT_SUMMARY.md"
move_file "ICON_MAPPINGS.md"
move_file "LAYOUT_COMPARISON_GUIDE.md"
move_file "LAYOUT_VARIANTS_COMPARISON.md"
move_file "MOBILE_VISUAL_ANALYSIS_REPORT.md"
move_file "MOBILE_vs_DESKTOP_EXPLANATION.md"
move_file "PLAY_CREATIVITY_STANDARDIZED_SUMMARY.md"
move_file "SIMPLE_BACK_BUTTON_SUMMARY.md"
move_file "SKILLS_LAYOUT_UPDATE.md"
move_file "STANDARDIZED_BACK_BUTTON_ALL_PAGES_SUMMARY.md"
move_file "STANDARDIZED_BACK_BUTTON_SUMMARY.md"
move_file "UI_IMPROVEMENTS_SUMMARY.md"
move_file "UNIVERSAL_MOBILE_TYPOGRAPHY.md"

echo ""
echo "Category 3: Old GCP/Database Guides (Redundant)"
echo "----------------------------------------------"
move_file "EXACT_GCP_SERVICES_FREE_VS_PAID.md"
move_file "FLEXIBLE_DATA_MANAGEMENT_SOLUTION.md"
move_file "GCP_COSTS_INR.md"
move_file "GCP_DATABASE_SETUP_GUIDE.md"
move_file "GCP_ENTERPRISE_SOLUTION.md"
move_file "GENAI_CREDITS_USAGE_GUIDE.md"
move_file "HYBRID_ARCHITECTURE_STRATEGY.md"
move_file "IMPROVED_FIRESTORE_STRUCTURE.md"
move_file "REAL_COMPANY_GCP_USAGE.md"
move_file "REVISED_RECOMMENDATION_POSTGRESQL.md"
move_file "SCALABLE_COST_BREAKDOWN.md"
move_file "WHY_POSTGRESQL_REDIS_COST_DAILY.md"

echo ""
echo "Category 4: Old Google Sheets Documentation"
echo "------------------------------------------"
move_file "GOOGLE_SHEETS_IMPLEMENTATION_GUIDE.md"
move_file "GOOGLE_SHEETS_SETUP_GUIDE.md"
move_file "GOOGLE_SHEETS_SYNC_GUIDE.md"
move_file "ROBUST_ACTIVITY_CREATION_STRATEGY.md"
move_file "SAMPLE_DATA_PREVIEW.md"
move_file "NEW_ACTIVITIES_LOCATION_GUIDE.md"

echo ""
echo "Category 5: Old Git/Testing Guides (Redundant)"
echo "---------------------------------------------"
move_file "GITHUB_ACTIONS_SETUP.md"
move_file "MANUAL_GITHUB_ACTIONS_SETUP.md"
move_file "PROPER_GIT_WORKFLOW.md"
move_file "QUICK_DECISION_SUMMARY.md"
move_file "QUICK_GIT_COMMANDS.md"
move_file "HOW_TO_TEST_AGENTS.md"
move_file "TESTING_INSTRUCTIONS.md"
move_file "STAGING_IMPORT_GUIDE.md"

echo ""
echo "Category 6: Old README/Account Setup (Replaced)"
echo "----------------------------------------------"
move_file "README_AGENT_SYSTEM_V2.md"
move_file "README_SYNC_WORKFLOW.md"
move_file "NEW_ACCOUNT_SETUP_GUIDE.md"
move_file "LATEST_CUSTOMER_INSTRUCTIONS.md"
move_file "LOCAL_vs_REMOTE_EXPLANATION.md"

echo ""
echo "Category 7: Version/Agent Documentation (Old)"
echo "--------------------------------------------"
move_file "VERSION_1_DOCUMENTATION.md"
move_file "VERSION_1_VS_2_DECISION_GUIDE.md"
move_file "VERSION_2_COMPLETE_PLAN.md"
move_file "VERSION_MIGRATION_STRATEGY.md"
move_file "VERTEX_AI_MIGRATION_COMPLETE.md"
move_file "PROFILE_AGENT_UPDATE_SUMMARY.md"

echo ""
echo "Category 8: Miscellaneous Old Docs"
echo "---------------------------------"
move_file "MISSING_DATA_ANALYSIS.md"
move_file "SIMPLE_SOLUTION.md"
move_file "SIMPLE_LOG_VIEWING.md"

echo ""
echo "Category 9: Old JS Debug Files"
echo "-----------------------------"
move_file "check-auth-status.js"
move_file "check-console-errors.js"
move_file "check-data-duplicates.js"
move_file "check-firebase-settings.js"
move_file "comprehensive-logout-test.js"
move_file "debug-auth-deep.js"
move_file "debug-auth-state.js"
move_file "debug-dropdown.js"
move_file "debug-logout-issue.js"
move_file "debug-state.js"

echo ""
echo "✅ AGGRESSIVE CLEANUP COMPLETE!"
echo "==============================="
echo ""
echo "📊 Summary:"
echo "  Moved to backup: ~60 old/temporary documentation files"
echo "  Moved to backup: ~10 JS debug files"
echo ""
echo "📦 Backup location: $BACKUP_DIR"
echo ""
echo "✅ Kept (Essential files only):"
echo "  - New deployment system (14 docs + 4 scripts)"
echo "  - Tracking files (CHANGELOG, DEPLOYMENT_LOG, CURRENT_VERSION)"
echo "  - Technical references (Firebase, Agent, Database docs)"
echo "  - Application code (src/, backend/, public/)"
echo "  - Config files (package.json, firebase.json, etc.)"
echo ""
echo "Your folder is now VERY clean and GitHub-ready! ✅"
echo ""

