name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        cat > .env << EOF
        REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}
        REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}
        REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
        REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
        REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}
        EOF
      
    - name: Build the app
      run: npm run build
      
    - name: Verify Node.js version
      run: |
        node --version
        npm --version
        which node
        which npm
        
    - name: Setup Google Cloud CLI and Service Account
      run: |
        # Install Google Cloud CLI
        curl -sSL https://sdk.cloud.google.com | bash
        echo "$HOME/google-cloud-sdk/bin" >> $GITHUB_PATH
        
        # Setup service account
        cat > firebase-service-account.json << 'EOF'
        ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        EOF
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/firebase-service-account.json"
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-service-account.json" >> $GITHUB_ENV
        
        # Authenticate with service account
        gcloud auth activate-service-account --key-file=firebase-service-account.json
        gcloud config set project unschooling-464413
        
        echo "✅ Service account authenticated with Google Cloud"
        
    - name: Deploy to Firebase Hosting
      run: |
        npm install -g firebase-tools@latest
        
        # Use service account authentication
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/firebase-service-account.json"
        
        # Deploy using service account
        echo "🚀 Deploying with service account authentication..."
        firebase deploy --only hosting --project unschooling-464413
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json 